# AgentShield Agent Behaviour Emulator — Copilot bootstrap

> This file lives at `.agentshield/agent-emulator-bootstrap.md` and
> was generated by `agentshield scan`. It tells GitHub Copilot how
> to walk the agent's runtime pipeline statically from source, inject
> catalogued attack classes at each pipeline step, and predict what
> the agent would do.
>
> This replaces the earlier `redteam-simulate` / `redteam-plan` pair
> with a single, more honest skill — see the *Honesty contract*
> below.

## Honesty contract — read this first

**Positioning (canonical):**

> AgentShield's behaviour emulator runs catalogued adversary
> tactics (OWASP LLM / Agentic Top-10, MITRE ATLAS) against an
> agent's runtime pipeline — statically, from source — and
> reports per-step verdicts with code citations. **Adjacent to
> adversary emulation but methodology-distinct:** we walk the
> pipeline, we don't fire payloads; we test pattern classes, not
> specific threat actors.

What this means concretely:

- **Not red-teaming.** A real red-team engagement fires payloads
  at a live target. We don't.
- **Not strict-MITRE adversary emulation.** That impersonates a
  specific named threat actor (APT29, FIN7, etc.) using their
  documented playbook. We don't pick a threat actor; we test
  catalogued *pattern classes* drawn from OWASP + ATLAS.
- **Not dynamic security testing.** No live agent is talked to;
  nothing leaves the IDE.
- **What it IS:** Copilot walks the agent's runtime pipeline
  statically from source, predicts the behaviour at each step,
  and reports what would happen under each catalogued attack
  class — with code citations for every prediction.

| | Real red-teaming | This skill | Static review |
| -- | -- | -- | -- |
| Live agent endpoint required | yes | **no** | no |
| Payloads actually sent | yes | **no** | no |
| Pipeline behaviour modelled | yes (observed) | **yes (predicted from code)** | no |
| Per-step injection surface | yes | **yes** | no |
| Right to claim *"attack landed"* | yes | **no** — only *"would land based on code"* | no |
| Stronger than substring scanning | yes | **yes** | partial |

What this skill **does** add over static review:

- Walks the agent's *runtime pipeline* — user prompt → RAG → system
  prompt → planner → tool choice → tool output → re-planning →
  final answer — and predicts the behaviour at every step.
- Injects catalogued attack classes at the **specific pipeline step
  they target** (prompt injection at the user-prompt step;
  retrieved-doc poisoning at the RAG step; fake tool outputs at the
  tool-output step; recursive injection at the re-planning step).
- Uses **generic catalogue payloads** for the attacker side —
  *no insider knowledge from the source code is pre-baked into
  payloads*. The intelligence comes from what the agent leaks back,
  not from what AgentShield read.

What this skill **does not** do:

- Send any payload over the wire — nothing leaves the IDE.
- Verify dynamic behaviour against a real runtime — the predictions
  are only as accurate as the code Copilot can see.
- Substitute for runtime probe against a staging deployment. When a
  customer has staging, that should still be run.

The report labels this as **"Behaviour emulator — pipeline trace"**,
not *"simulated kill-chain"*, so reviewers don't mistake forecasts
for captured exploits.

## TL;DR for the developer

You ran `agentshield scan`. Tier 1 + Tier 2 found defects in the
code as code patterns. The agent-emulator walks the agent's runtime
pipeline from those same files and predicts how each catalogued
attack class would propagate through it, citing the file:line that
governs each step's behaviour.

To run the emulator:

1. Open this repo in VS Code or JetBrains with GitHub Copilot
   enabled.
2. Open Copilot Chat.
3. Paste this prompt:

   ```
   @workspace Please run the AgentShield agent behaviour emulator.

   Read the instructions at
   .agentshield/agent-emulator-instructions.md and the output
   schema at .agentshield/agent-emulator-output-schema.md.

   Walk the agent's runtime pipeline from source code (user prompt
   → RAG → system prompt → planner → tool choice → tool output →
   re-planning → final answer). For each catalogued attack class
   listed in the instructions, identify the pipeline step(s) it
   targets, predict the pipeline behaviour under that attack, and
   cite the file:line evidence for every prediction.

   Use the GENERIC catalogue payloads exactly as shipped — do not
   adapt the attacker-side text from source code. The intelligence
   comes from what the agent reveals, not from what you read in
   the repo.

   Write your pipeline emulations to
   .agentshield/agent-emulation.json following the schema exactly.
   Mark inconclusive when the relevant pipeline step isn't present
   — do not fabricate behaviour.
   ```

4. Run `agentshield merge <repo>` to produce the unified report.
   The merger renders each emulated attack as a **per-step pipeline
   trace** with the catalogue payload at the top, the agent's code
   walked step-by-step, and a verdict + Fix per finding.

## What "pipeline step" means here

The agent emulator decomposes a single agent request into **eight
discrete steps**. Each step is a place where:

1. The agent does something (read input, retrieve context, choose
   a tool, etc.)
2. There is **specific code in the repo** that implements that
   something.
3. There is a **specific attacker-controllable input** that targets
   that step.
4. There is a **specific defensive control** that should be present.

| # | Step | What it does | Attacker control | Defensive control |
| -- | -- | -- | -- | -- |
| 1 | **User prompt** | Reads chat input from the request body | Direct attacker input | Input sanitiser, guardrail |
| 2 | **RAG context** | Retrieves documents / vector chunks / memory recall | Poisoned retrieved doc, poisoned vector entry | Provenance check, content classifier on retrieval |
| 3 | **System prompt** | Loads the developer-supplied system instructions | Indirect — system prompt itself may be tampered upstream | Immutable / signed prompt, never echoed |
| 4 | **Planner** | LLM decides which tool to call + args | Prompt-injected instructions override the planner | Schema-validated tool calls, intent classifier |
| 5 | **Tool choice** | Dispatcher resolves the tool name + executes | Wrong tool selected; tool fired without auth | Signed-identity check, allow-list, HITL for destructive |
| 6 | **Tool output** | Tool returns a string / object back to the agent | Crafted tool output that re-injects instructions | Output validator, schema check, content classifier |
| 7 | **Re-planning** | LLM consumes tool output, plans next step | Re-injection via tool output; runaway loops | Loop limiter, intent re-evaluation |
| 8 | **Final answer** | LLM produces user-visible reply | Output may leak system prompt, sensitive context | Output scrubber, secret-redaction filter |

Not every agent has every step. A single-shot chain-invoke agent
collapses steps 4–7 into one LLM call. A RAG agent has a fat step 2.
A multi-agent orchestrator has multiple round-trips through 4–7.
The emulator's first job is to map what *this specific agent* has;
the second is to inject attacks at the steps that exist.

## When to run this vs the static Tier 2 vs the runtime probe

| | When to run | What it tells you |
| -- | -- | -- |
| Tier 2 (Copilot LLM-as-judge) | Every scan | TP/FP/CD verdict on each Tier 1 pattern; flags architectural defects in §5.5 |
| **Agent emulator** (this skill) | After Tier 2 | Predicts how those defects propagate through the agent's pipeline; produces per-step traces with attack class verdicts |
| Runtime probe (separate workflow) | When you have a staging deployment | Captures actual responses to actual payloads sent over the wire |

The emulator sits between static review and runtime probe — semi-
dynamic, deterministic, code-grounded, and clearly labelled as
forecast not proof.
